name: flutter_flexui_example
description: Example for flutter package for build Flexible UI for diference screens
publish_to: none
version: 2.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flexui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
