name: flutter_flexui
description: Flutter package for build Flexible and beautiful UI to considers different screen sizes. 
version: 0.1.6
homepage: https://dipdev.studio
issue_tracker: https://gitlab.com/dipdev.studio/open-source/flutter-flexui/issues
repository: https://gitlab.com/dipdev.studio/open-source/flutter-flexui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^1.0.2
  universal_html: ^1.2.4
  device_info: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter