name: flutter_flexui
description: Flutter package for build Flexible and beautiful UI to considers different screen sizes.
version: 1.2.1
homepage: https://dipdev.studio
issue_tracker: https://gitlab.com/dipdev.studio/open-source/flutter/flutter-flexui/issues
repository: https://gitlab.com/dipdev.studio/open-source/flutter/flutter-flexui

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  universal_html: ^2.2.3
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
