name: flutter_flexui
description: Flutter package for build Flexible and beautiful UI to considers different screen sizes. 
version: 1.1.1
homepage: https://dipdev.studio
issue_tracker: https://gitlab.com/dipdev.studio/open-source/flutter-flexui/issues
repository: https://gitlab.com/dipdev.studio/open-source/flutter-flexui

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  universal_html: ^2.0.8
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0