name: flutter_flexui
description: Flutter package for build Flexible and beautiful UI to considers different screen sizes. 
version: 0.0.1+1
homepage: https://dipdev.studio
issue_tracker: https://gitlab.com/dipdev.studio/open-source/flutter-flexui/issues
repository: https://gitlab.com/dipdev.studio/open-source/flutter-flexui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: